apiVersion: flinkoperator.k8s.io/v1alpha1
kind: FlinkCluster
metadata:
  name: beam-flink-cluster
spec:
  image:
    name: flink:1.8.1
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "1Gi"
  taskManager:
    replicas: 2
    resources:
      limits:
        memory: "2Gi"
    sidecars:
      - name: beam-worker-pool
        image: gcr.io/google.com/hadoop-cloud-dev/apachebeam_python3.7_sdk:2.18.0.dev
        args: ["--worker_pool"]
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
