apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beam-job-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beam-job-server
    spec:
      containers:
        - name: beam-job-server
          image: gcr.io/google.com/hadoop-cloud-dev/flink-job-server:1.8-dev
          imagePullPolicy: Always
          args:
            - "--flink-master=beam-flink-cluster-jobmanager:8081"
            - "--artifacts-dir=gs://dagang-test/beam/artifacts/"
---
apiVersion: v1
kind: Service
metadata:
  name: beam-job-server
spec:
  ports:
    - name: job
      port: 8099
      targetPort: 8099
    - name: artifact
      port: 8098
      targetPort: 8098
  selector:
    app: beam-job-server
